version: "2"
linters:
  default: all
  disable:
    - exhaustruct
    - funlen
    - gocognit
    - ireturn
    - maintidx
    - mnd
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          deny:
            - pkg: log
              desc: use log/slog exclusively
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        text: do not define dynamic errors, use wrapped static errors instead
      - linters:
          - cyclop
          - dupl
          - funlen
          - varnamelen
        path: _test.go$
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
