run:
  timeout: 5m
output:
  sort-results: true
linters:
  enable-all: true
  disable:
    - execinquery # deprecated: archived by owner
    - exhaustruct # zero values of fields should be respected
    - exportloopref # deprecated: no longer relevant as of Go1.22
    - funlen # redundant with cyclop
    - gocognit # redundant with cyclop
    - gofumpt # prefer standard gofmt
    - goimports # rely on gci instead
    - gomnd # deprecated: renamed to mnd
    - ireturn # useful for
    - maintidx # redundant with cyclop
    - nlreturn # stylistic choice
    - nonamedreturns # yes, named returns
    - testpackage # not necessary
    - wsl # stylistic choice
    - wrapcheck # don't always need to wrap errors
linters-settings:
  depguard:
    rules:
      main:
        files: [$all]
        deny:
          - pkg: log
            desc: use log/slog exclusively
issues:
  exclude-rules:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - linters: [err113]
      text: "do not define dynamic errors, use wrapped static errors instead"
    # loosen restrictions on test code
    - path: '_test.go$'
      linters:
        - cyclop
        - dupl
        - varnamelen
        - funlen
