name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [stable]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
      - name: Generate
        run: |
          make clean
          make format
          make generate
          make generate-check
      - name: Test
        run: make test
      - name: Lint
        run: make lint